### ISSUE TITLE
What range of Emacs version do we support?

### ISSUE THREAD

**Issue by lddubeau** [emacs-typescript/typescript.el#100]
We've figured it out for [tide](https://github.com/ananthakumaran/tide/issues/292).

Maybe just adopt the same rules as tide? Or is there some other consideration I'm forgetting?

I plan to add Emacs 26.1 to the list of Emacs versions tested but I noticed 24.3 is still in the list and maybe should be removed.

**Comment by josteink** [comment]
I don't see any desperate need to deprecate old versions of Emacs if the code we have right now is chugging along fine on those versions.

However, the second any of those really old versions are preventing new stuff from being added, I'm OK dropping support.

Are there any pressing issues right now, or are you just trying to stay ahead of the curve? :)

**Comment by lddubeau** [comment]
I'm on 26.1 now so I'm going to modify `.travis.yml` to include 26.1. Might as well take care of any other edits while I'm at it.

I've sometimes adopted the "don't drop a version until it fails in testing" approach. It works fine when I'm the only active developer or when *everyone* knows the rule. I'm concerned about a contributor getting an error on a version that could be dropped from testing, not realize that the solution is to drop the version, and instead spend time researching a way to make their code work on that old version.

**Comment by josteink** [comment]
Fair enough. There's multiple ways to solve that problem as I see it:

* document it in a `CONTRIBUTING.md` file of sorts.
* let CI fail when it fail, and handle it in a PR discussion.
* pre-emptively drop it from `.travis.yml`, like you suggest.

Either approach is fine by me, but I guess the latter approach means least work, and means we won't have to keep this in mind for the future.

Also... The *current* code will still work on 24.3, so I guess removing it from travis won't mean any effective changes really. The second we cross the compatibility-barrier, it would have been dropped anyway.
