### ISSUE TITLE
Indent setting from EditorConfig 

### ISSUE THREAD

**Issue by tvainika** [emacs-typescript/typescript.el#101]
I tried to use editorconfig-mode and typescript-el together and noticed that editorconfig indentation settings are not used in typescript mode.  It would be nice to have these two working out of the box if possible.

**Comment by lddubeau** [comment]
I use `editorconfig-mode` with `typescript-mode` without any issue. I did not have to do anything special. It just worked.

**Comment by tvainika** [comment]
In my `~/.emacs` I've:
```
(add-hook 'typescript-mode-hook (lambda ()
				  (editorconfig-mode 1)))
```
and in source directory `.editorconfig` I've:
```
root = true

[*]
indent_style = space
indent_size = 2
```

But when opening `.ts` files with Emacs the indentation level is set to 4, not 2 unless I explicitly change custom variable `typescript-indent-level`. But if this is supposed to work, I guess I've to debug more.

typescript-mode-el v0.3 installed from MELPA stable channel.

**Comment by lddubeau** [comment]
Maybe your glob is too strict. I now the glob `[*]` would not work for any of my projects. If you have `.editorconfig` at the top of your project, but, for instance, put your TS files in a `src/` subdirectory, then the pattern `[*]` won't match the files in the subdirectory. To match into subdirectories, you'd have to use `[**]` or use `[**.ts]` if you want to restrict the setting only to `.ts` files.

**Comment by tvainika** [comment]
Something havoc in my Emacs or editorconfig installation. Works with clean setup.
