### ISSUE TITLE
Function keyword highlight incorrect.

### ISSUE THREAD

**Issue by jcs090218** [emacs-typescript/typescript.el#103]
If the function name the same as the keyword, the function also get highlighted.

### Screenshot ###
![ts-mode-bug](https://user-images.githubusercontent.com/8685505/53959802-99b3cd80-411f-11e9-96c7-a31a3f48ba86.png)

**Comment by lddubeau** [comment]
We welcome PRs to fix this.

**Comment by jcs090218** [comment]
I would like to help, but I'm assure I'm bad at `regexp`. My solution wouldn't be the best, maybe it would be good to have `help-wanted` tag on this issue?

**Comment by lddubeau** [comment]
@jcs090218 Yeah, we've gotten into the habit of saying "PRs welcome".

@josteink Any objection to the systematic use of the "help-wanted" label for those cases where we'd say "PR welcome"? I think right now it would mean turning it on for all (or almost all) issue reports.

**Comment by josteink** [comment]
I was about to make a comment that this label is implicitly applicable to any unsold an open issue which we have in this repo. 

That’s said I see no problem with being a little more explicit about it. Feel free to tag any and all issues you like 👍

**Comment by Fuco1** [comment]
This is a very simple fix.  Since the functions are fontified after keywords (which are level 2) all that is needed is to allow font-lock to overwrite the existing fontification.  I'll make a PR in a couple minutes.
