### ISSUE TITLE
Infinite loop in typescript--forward-expression

### ISSUE THREAD

**Issue by ramblehead** [emacs-typescript/typescript.el#105]
The following snippet is the current implementation of ```typescript--forward-expression``` function which I have from melpa:

```elisp
(defun typescript--forward-expression ()
  "Move forward over a whole typescript expression.
This function doesn't move over expressions continued across
lines."
  (loop
   ;; non-continued case; simplistic, but good enough?
   do (loop until (or (eolp)
                      (progn
                        (forward-comment most-positive-fixnum)
                        (memq (char-after) '(?\, ?\; ?\] ?\) ?\}))))
            do (forward-sexp))

   while (and (eq (char-after) ?\n)
              (save-excursion
                (forward-char)
                (typescript--continued-expression-p)))))
```

The following is the typescript which causes ```typescript--forward-expression```  to go into infinite loop:

```typescript
fetch('http://localhost:8529/_db/_system/land', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    Accept: 'application/json',
  },
  body: JSON.stringify({
    query: `{
      query GetElement {
        element(id: "0000") {
          collection
          id
          name
          description
        }
      }
    }`,
  }),
})
  .then(r => r.json())
  .then(data => console.log('data returned:', data));
```
If the point is placed in the beginning of ```fetch``` and ```typescript--forward-expression```  is executed, it would move point between closing bracket of ```fetch``` and first ```.then(``` line indefinitely.

Here is a ```typescript--forward-expression```  fix I am currently using:

```elisp
(defun typescript--forward-expression ()
  "Move forward over a whole typescript expression."
  (loop
   do (progn
        (forward-comment most-positive-fixnum)
        (loop until (or (eolp)
                        (progn
                          (forward-comment most-positive-fixnum)
                          (memq (char-after) '(?\, ?\; ?\] ?\) ?\}))))
              do (forward-sexp)))
   while (and (eq (char-after) ?\n)
              (save-excursion
                (forward-char)
                (typescript--continued-expression-p)))))
```
I have not yet seen any additional side effects with this solution.

Thank you for the typescript-mode!

**Comment by lddubeau** [comment]
Thank you for providing a complete report. I used the reproduction case and was able to immediately reproduce the issue here. So I confirm this is a real bug.

I'm pressed for time these days. So I'm not able to get to this quickly. If you are able to, you could submit a PR that includes a test case for the error you found.

**Comment by ramblehead** [comment]
Thank you for the quick response. I will try look into the test case this weekend.
