### ISSUE TITLE
Let declaration with assertion + without value => incorrect indentation

### ISSUE THREAD

**Issue by paxperscientiam** [emacs-typescript/typescript.el#107]
Hello!

There is an indentation bug that arises when using type assertion on let variables without an explicit default value. Well, at least in the present case.

Minimal example.:
```ts
const variable: number = 214

let $img: JQuery<HTMLImageElement>
    if (variable != null) {
        //
    }


let $img2: JQuery<HTMLImageElement> = null
if (variable != null) {
    //
}
```

**Comment by lddubeau** [comment]
The problem is with `<HTMLImageElement>`. If I remove it from the case that is not indented properly, the problem goes away.

I'll take a look at the indentation logic and come up with a solution.

**Comment by lddubeau** [comment]
I've put a fix on this branch:

https://github.com/emacs-typescript/typescript.el/tree/fix/indentation

@paxperscientiam Is it possible for you to try that fix and see whether it has any unintended consequences? I've added a test just for it and the change has not caused any old indentation test to fail but it would be good to double check nonetheless. Semi-colons are mandatory in all my projects so I don't have good code samples to check it. I also suspect the indentation test for the mode is probably biased towards testing code that uses semi-colons. Thanks.

**Comment by paxperscientiam** [comment]
@lddubeau Awesome. I'll give it a looksy.

**Comment by lddubeau** [comment]
@paxperscientiam Thanks for confirming. By the way, new comments generate emails but edits do not. I received an email with "Awesome. I'll give it a looksy." and then that was that. I was under the impression that you had still not gotten around to doing it until just now when I happened by chance to click on this issue and see your edit. I'm going to merge the fix ASAP.

**Comment by paxperscientiam** [comment]
@lddubeau Oh, I didn't know that about edits. Thanks for the heads up.

I appreciate your effort!
