### ISSUE TITLE
typescript-indent-line: Arithmetic error

### ISSUE THREAD

**Issue by andreineculau** [emacs-typescript/typescript.el#117]
if `.editorconfig` says `indent_size = none` which is a way to say editorconfig will not handle indentation for this file

**Comment by andreineculau** [comment]
investigating a bit, but it seems it's not related to editorconfig.

when `indent_size = none` there is no indentation set by editorconfig so `typescript-indent-line` ends up calling `(indent-line-to 4)` (the default indentation)

I can call `indent-line-to` with <= 2, but nothing bigger for some reason.

afaics the situation doens't change when turning off all other modes, thus i'm leaving this open

**Comment by josteink** [comment]
Hey there and thanks for the report!

As someone not using `.editorconfig` myself... And I'm not sure I fully understand.

Could you come up with a minimal use-case/repo with what you expected to happen vs what really happened, and where the problem you encounter can easily be reproduced, and thus debugged?

**Comment by lddubeau** [comment]
Without a case to reproduce this, we cannot move forward. This can be reopened once we get such a case.
