### ISSUE TITLE
Help with/support for dir-locals.el

### ISSUE THREAD

**Issue by t3hmrman** [emacs-typescript/typescript.el#123]
`typescript-mode` doesn't seem to support [dir-locals](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html), I've tried with a `.dir-locals.el` file that looks like this:

```elisp
((typescript-mode (typescript-indent-level . 4)))
```
Does `typescript-mode` support dir local variables?

[EDIT] - Here's a work-around that does work for me:

```elisp
;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((typescript-mode
  (typescript-indent-level . 4)
  (eval . (setq typescript-indent-level 4))))
```

And in `~/.emacs`/(or the block of settings that `customize` outputs):

```elisp
 '(safe-local-variable-values (quote ((eval setq typescript-indent-level 4))))
```

Also, I just noticed but ignore the fact that I'm setting it to 4 (I've changed the variable to a different value with customize -- this would be the same problem if I was setting it to 2)

**Comment by lddubeau** [comment]
I cannot reproduce the problem. If I take your first block of code but change 4 to a value that I'm sure is not a default, put it in a `.dir-locals.el` file in a new empty directory and then create `.ts` files in there, then the indent level is set to what is in the `.dir-locals.el` file. (If I remove it, it goes back to the default.) I've tried both with my ever-opened-emacs and with a new emacs without any custom configuration (`emacs -q`). It works in both cases.

Most likely there is something else interfering with our configuration.

The way forward for you to get action on this would be for you to produce a MCVE using `emacs -q`. When you do this, typescript won't be loaded by default, but you can find the `typescript-mode.el` file and eval that buffer as one of the initial steps of the MCVE. If you produce a MCVE and we can reproduce the issue, then we can reopen.

**Comment by t3hmrman** [comment]
thanks for taking a look @lddubeau this must have been something on my end -- will keep looking on my end and update if I find what was messing up the config.
