### ISSUE TITLE
Add tsx to auto-mode-alist

### ISSUE THREAD

**Issue by yasushi-saito** [emacs-typescript/typescript.el#130]
Changing the next-to-last line to:

(add-to-list 'auto-mode-alist '("\\.tsx?$" . typescript-mode))

should work.

**Comment by lddubeau** [comment]
This mode does not currently support tsx.  We're not going to add `.tsx` to the `auto-mode-alist` until the mode does support tsx. Adding it to the list without proper support would just confuse users who (reasonably) expect that if the mode modifies `auto-mode-alist` to associate tsx with this mode, then this mode supports tsx.

See #4 

In order for tsx support to be added, someone who needs this support will have to step up and do the work. Given that none of the collaborators on this project have done anything about it in 4 years, I would not wait for us to act.

**Comment by josteink** [comment]
If that change works for you and the way you use TSX, good for you. You can add it to your `init.el` and ensure everything works as you like it on your end.

On our part though, I agree with @lddubeau: I don't want to give other Emacs-users a false sense of what they can expect to work and to be supported. In that respect it's IMO better to be conservative than liberal. Users (like yourself) are free to expand the auto-mode list depending on their own preferences, after all.

Until we have a "regular" TSX-user onboard who is willing to test and review TSX-related changes, I doubt `typescript-mode` will be able to support this.
