### ISSUE TITLE
Single-line object-constructors are fontified incorrectly when prefixed on a line with a generic operation

### ISSUE THREAD

**Issue by josteink** [emacs-typescript/typescript.el#131]
Take the line of typical REST service boilerplate:

````typescript
return this.httpClient.post<IContactOrPerson[]>(url, { Name: name, ContactId: contactId })
````

In Emacs this gets fontified incorrectly:
![image](https://user-images.githubusercontent.com/411338/76193925-5df58d00-61e5-11ea-8dcb-b01b503fbb4c.png)

Modified to include a line-break it almost looks good, but still has issues:

![image](https://user-images.githubusercontent.com/411338/76194298-2b985f80-61e6-11ea-828e-1549899488c9.png)

This can be verified using the following ERT test-case:

````elisp
(ert-deftest font-lock/type-name-generics-negatives ()
  "Do not fontify other common uses with : in syntax."

  (test-with-fontified-buffer
      "return this.httpClient.post<IContactOrPerson[]>(url, { Name: name, ContactId: contactId });"
    (should (not (eq (get-face-at "url" 'font-lock-type-face))))
    (should (not (eq (get-face-at "name" 'font-lock-type-face))))
    (should (not (eq (get-face-at "contactId" 'font-lock-type-face))))))
````

From inspecting the font-highlighting using `font-lock-studio` the following rule is singled out as the culprit: https://github.com/emacs-typescript/typescript.el/blob/bc37bc4b1527f0ad382bbdcecf2ea3623717aebb/typescript-mode.el#L1992-L1998

@tam5 : You were the one who introduced this code. Can you take a look at this case and see if you can make it behave better? (And at least pass my ERT test-case?)

**Comment by josteink** [comment]
I've looked into this some more, and this code contains elements from both PR #110 and #119, but as far as I can see, the error was already there in #110.

**Comment by josteink** [comment]
Looking futher into this test-case it only seems to fail when the generic type-argument contains an array.

Consider the following examples:

````typescript
	goodTestCase<Test>(boo: hoo, zoo:doo ) {
		
	}

	basTestCase<Test[]>(boo: hoo, zoo:doo ) {
		
	}
````

This renders as following:

![image](https://user-images.githubusercontent.com/411338/76195787-5b953200-61e9-11ea-9ab7-eedb43c6554f.png)

This makes the error less severe, as not *all* generic operations are affected, but it's still annoying.

**Comment by josteink** [comment]
After I merged #129 to git `master`, I'm able to make this look "good" with the following patch:

````diff
@@ -1994,8 +1994,8 @@ This performs fontification according to `typescript--class-styles'."
 
     ;; generics support
     ,(list
-      (concat typescript--name-re "\\s-*" "<\\s-*" typescript--name-start-re)
-      (list (concat "\\(" typescript--name-re "\\)\\(\\s-*>[^<]*\\)?")
+      (concat typescript--name-re "\\s-*" "<\\s-*[A-Z]")
+      (list (concat "\\(" typescript--type-name-re "\\)\\(\\s-*>[^<]*\\)?")
             '(backward-char)
             '(end-of-line)
             '(1 font-lock-type-face)))
````

I'll create a PR for it.

**Comment by josteink** [comment]
Update: While my above patch solves the simple test-cases of goodTestCase and badTestCase, it doesnt work for more complex scenarios:

![image](https://user-images.githubusercontent.com/411338/76197188-fa229280-61eb-11ea-84e3-223cc26dc5a0.png)

Now it's just weird. I'll leave it at this for now, and hopefully you can work this out @tam5.

**Comment by tam5** [comment]
I have seen this, not ignoring it. And @josteink you are right about the ending being the issue. It is like this I think so that we can handle nested generics i.e. `method<Array<T>>()`. Will need to think of a way to accommodate both.

**Comment by josteink** [comment]
Typescript-support is now part of core Emacs, where this is fixed. Closing this issue.
