### ISSUE TITLE
can't seem to indent props in JSX expression

### ISSUE THREAD

**Issue by orzechowskid** [emacs-typescript/typescript.el#138]
software versions:
- emacs 27.1 ; also tried with emacs-snapshot 28.0.50 (latest snapshot from the ubuntu-elisp ppa)
- typescript-mode 20200817.817

steps to reproduce:
1. `emacs -Q`
2. open a typescript file
3. `M-x typescript-mode`
4. write the following code:
```js
  const MyComponent = () => {
    return (
      <div className="foo" />
    );
  };
```
5. attempt to put the JSX prop on its own line.

desired output:
```js
  const MyComponent = () => {
    return (
      <div
        className="foo"
      />
    );
  };
```
actual output:
```js
const MyComponent = () => {
  return (
    <div
    className="foo"
      />
  );
};
```
possibly relevant info:
- `indent-tabs-mode` is set to nil
- `typescript-indent-level` is set to 2
- setting `typescript-expr-indent-offset` to 2 appears to add 2 spaces of indentation to the closing `/>` but nothing else

does this mode derive from any other modes for which indentation-related variables exist?  did I forget to configure something in a different customization-group?

thanks for any help you can provide.

**Comment by josteink** [comment]
Please search existing issues. JSX/TSX is not yet actually supported:

https://github.com/emacs-typescript/typescript.el/issues/4
