### ISSUE TITLE
typescript new keyword 'override' highlight 

### ISSUE THREAD

**Issue by psychehao** [emacs-typescript/typescript.el#149]
need typescript new keyword 'override' highlight

**Comment by psychehao** [comment]
(defconst typescript--keyword-re
  (typescript--regexp-opt-symbol
   '("abstract" "any" "as" "async" "await" "boolean" "bigint" "break" "case" "catch" "class" "const"
     "constructor" "continue" "declare" "default" "delete" "do" "else"
     "enum" "export" "extends" "extern" "false" "finally" "for"
     "function" "from" "get" "goto" "if" "implements" "import" "in" "instanceof"
     "interface" "keyof" "let" "module" "namespace" "never" "new" "null" "number" "object" "of"
     "private" "protected" "public" "readonly" "return" "set" "static" "string"
     "super" "switch"  "this" "throw" "true"
     "try" "type" "typeof" "unknown" "var" "void"
     "while"
     "override")) ; <= override keyword
  "Regexp matching any typescript keyword.")

**Comment by josteink** [comment]
Sounds like you've almost got a PR landed for this ;)
