### ISSUE TITLE
Bump Version Tag

### ISSUE THREAD

**Issue by phikal** [emacs-typescript/typescript.el#151]
Hi,

I wanted to add typescript-mode to [NonGNU ELPA](https://elpa.nongnu.org), but it seems that `typescript-mode.el` has not bumped it's version tag despite two subsequent releases since 0.1 (this is relevant because ELPA uses the commit that bumps the version to mark releases). Would it be possible to update this, and if you are interested in having typescript-mode on NonGNU ELPA maintaining it for subsequent releases?

**Comment by josteink** [comment]
I just pushed the v0.4 tag right now.

Hopefully that should make things slightly more up to date :)

**Comment by phikal** [comment]
The only thing missing now for NonGNU ELPA is updating the version attribute in the [package header](https://github.com/emacs-typescript/typescript.el/blob/master/typescript-mode.el#L23). It shouldn't matter that the v0.4 tag doesn't point to the bump-commit.

**Comment by josteink** [comment]
Done!

**Comment by phikal** [comment]
Great, I'll add the package then in the next batch, then update this thread in case you want to update your documentation and add an ELPA badge.

**Comment by theothornhill** [comment]
Hi!

It seems `typescript-mode` never was added to nongnu elpa, is that so?
What is missing to include it?

**Comment by phikal** [comment]
Nothing, I had just lost track of it. Sorry for the long delay, I have added it now: http://elpa.nongnu.org/nongnu/typescript-mode.html (as of writing the page is broken, but this will change as soon as the cron job updates the archive).
