### ISSUE TITLE
Missing debugger keyword

### ISSUE THREAD

**Issue by UwUnyaa** [emacs-typescript/typescript.el#164]
I've just looked at the source of this mode, since the lack of highlighting for `debugger` has been bugging me every time I wrote it to add a breakpoint. It seems like the issue is down to not having the keyword listed.

For context, the `debugger` keyword is reserved, and here's the relevant section in the ECMA-262 spec: https://262.ecma-international.org/12.0/#sec-keywords-and-reserved-words

**Comment by josteink** [comment]
Thanks for the feedback. Fixed now :)
