### ISSUE TITLE
Incorrect highlighting of keywords on latest commit

### ISSUE THREAD

**Issue by dchrzanowski** [emacs-typescript/typescript.el#174]
Keywords such as `if` or `for` are highlighted as functions when standalone or  in comments.

Test the following:
```typescript
if (true) { // if highlights as a function
}

for (const x in y) { // for highlights as a function
}

// same with the below
// if (true) {  
// }

// for (const x in y) {
// }

// foo bar object
```

For me the word `object` is highlighted as a function when in a comment.

Possibly caused by #172

**Comment by josteink** [comment]
Cc: @Fuco1

**Comment by Fuco1** [comment]
Will fix tonight

**Comment by Fuco1** [comment]
Thanks for the report @dchrzanowski, I've pushed a PR so it will be fixed after that is merged and released on melpa (or wherever you install from :))

**Comment by josteink** [comment]
Should be merged now, but MELPA isn’t instant, so give it at least 24h.

**Comment by dchrzanowski** [comment]
No problem at all. Thanks for your help guys!
