### ISSUE TITLE
Comment syntax highlighting issue

### ISSUE THREAD

**Issue by log0ymxm** [emacs-typescript/typescript.el#6]
The following comment breaks syntax highlighting for all lines following

```
// some comment :/
```

Example: 

![screen shot 2015-11-06 at 9 46 04 am](https://cloud.githubusercontent.com/assets/35297/11002642/4c948b76-846b-11e5-80ef-192d8f19aac8.png)

**Comment by lddubeau** [comment]
I cannot reproduce this issue.
